server:
  port: 8081
  servlet:
    context-path: /smartparking
spring:
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: false
      show-sql: true
      open-in-view: false
  datasource:
    url: jdbc:h2:mem:testDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    platform: h2