DROP TABLE IF EXISTS ROLES;
CREATE TABLE "ROLES" (
"ROLE_ID" INT PRIMARY KEY,
"NAME" VARCHAR2(255)
);

CREATE TABLE "APPUSER" (
    "USER_ID" INT PRIMARY KEY,
    "USERNAME" VARCHAR2(200),
    "PASSWORD" VARCHAR2(200),
    "ENABLED" VARCHAR2(4)
);

CREATE TABLE "USERS_ROLES" (
    "USER_ID" NUMBER(19,0) NOT NULL,
    "ROLE_ID" NUMBER(19,0) NOT NULL
);

CREATE TABLE "PARKING_SPOT" (
    "ID" INT PRIMARY KEY,
    "AREA" VARCHAR2(200),
    "LATITUDE" NUMBER(10,6),
    "LONGITUDE" NUMBER(10,6),
    "PIN_CODE" VARCHAR2(7)
);

CREATE TABLE "BOOKING" (
    "ID" INT PRIMARY KEY,
    "PARKING_SPOT" INT,
    "DATES_ID" INT,
    "PARKING_SPOT_ID" INT,
    "USER_USER_ID" INT
);

CREATE TABLE "DATES" (
    "ID" INT PRIMARY KEY,
    "START" TIMESTAMP,
    "END" TIMESTAMP,
    "BOOKING_ID" INT
);

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;